const CHANGE_CURRENT_SONG = 'CHANGE_CURRENT_SONG'
const CHANGE_CURRENT_SONG_INDEX = 'CHANGE_CURRENT_SONG_INDEX'
const CHANGE_PLAY_LIST = 'CHANGE_PLAY_LIST'
const CHANGE_PLAY_MODE = 'CHANGE_PLAY_MODE'
const PLAY_IN_SEQUENCE = 'PLAY_IN_SEQUENCE'
const PLAY_IN_LOOP = 'PLAY_IN_LOOP'
const PLAY_IN_RANDOM = 'PLAY_IN_RANDOM'
const CHANGE_LYRIC_LIST = 'CHANGE_LYRIC_LIST'
const CHANGE_CURRENT_LYRIC_INDEX = 'CHANGE_CURRENT_LYRIC_INDEX'

export {
  CHANGE_CURRENT_SONG,
  CHANGE_CURRENT_SONG_INDEX,
  CHANGE_PLAY_LIST,
  CHANGE_PLAY_MODE,
  PLAY_IN_SEQUENCE,
  PLAY_IN_LOOP,
  PLAY_IN_RANDOM,
  CHANGE_LYRIC_LIST,
  CHANGE_CURRENT_LYRIC_INDEX
}