const CHANGE_TOP_BANNERS = 'CHANGE_TOP_BANNERS'
const CHANGE_HOT_RECOMMEND = 'CHANGE_HOT_RECOMMEND'
const CHANGE_NEW_ALBUMS = 'CHANGE_NEW_ALBUMS'
const CHANGE_SOAR_RANKING = 'CHANGE_SOAR_RANKING'
const CHANGE_NEW_SONG_RANKING = 'CHANGE_NEW_SONG_RANKING'
const CHANGE_ORIGINAL_RANKING = 'CHANGE_ORIGINAL_RANKING'

export {
  CHANGE_TOP_BANNERS,
  CHANGE_HOT_RECOMMEND,
  CHANGE_NEW_ALBUMS,
  CHANGE_SOAR_RANKING,
  CHANGE_NEW_SONG_RANKING,
  CHANGE_ORIGINAL_RANKING,
}